sudo: required
services:
  - docker

language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - pip --version
  - pip install -r requirements.txt
  - docker --version
  - docker-compose --version

install:
  - pip install -r requirements.txt

before_script:
  - docker-compose -f src/sdc-tool/test/compose/sdc.yml pull

script:
  - cd src/sdc-tool/test; python -m pytest

after_script:

after_success:
