sudo: required
services:
  - docker

language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - pip --version
  - pip install -r requirements.txt
  - docker --version
  - docker-compose --version

install:
  - pip install -r requirements.txt

before_script:
  - ./build-scripts/pre-test

script:
  - ./build-scripts/test

after_script:

after_success:
